### PR TITLE
Add phpcs support for JavaScript

### PR DESCRIPTION
**Pull request by jacks0n**

### CODE REVIEW

**Comment by lcd047** [comment]
This is no longer needed.  With recent versions of syntastic it's possible to call checkers for "foreign" filetypes like this: `php/phpcs`.  You can use that with `:SyntasticCheck`, you can add it to `syntastic_*_checkers` etc.

**Comment by jacks0n** [comment]
Hey @lcd047, ah no worries, sorry I didn't realise. Should [`syntax_checkers/css/phpcs.vim`](https://github.com/vim-syntastic/syntastic/blob/master/syntax_checkers/css/phpcs.vim) be deleted then, since it's available in [`syntax_checkers/php/phpcs.vim`](https://github.com/vim-syntastic/syntastic/blob/master/syntax_checkers/php/phpcs.vim)?

**Comment by lcd047** [comment]
No, nothing should be either added or deleted until the async API is finished.

**Comment by jacks0n** [comment]
@lcd047 ok, no worries.

**Pull request closed without merging**
