### PR TITLE
Fix bug when Syntastic hasn't been loaded as a script

### PR DESCRIPTION
**Pull request by Tav0**
- On-demand loading of plugin manager conflicted with getting Syntastic version.

### CODE REVIEW

**Comment by lcd047** [comment]
What problem does this solve?

**Comment by lcd047** [comment]
Ping?

**Comment by Tav0** [comment]
Hi @lcd047, sorry for the late reply. I use the [vim-plug option](https://github.com/junegunn/vim-plug#plug-options) `on` (on-demand loading) and I tend an error (pic below) every time I do `:SyntasticInfo`

screen shot 2017-01-04 at 5 07 15 am

Thus, this PR solves this problem.

The reason for this bug is in the code when loading Syntastic version, it is assuming Syntastic will be loaded when VIM starts up, which in my case isn't so I have made it so that it can still grab the constant variable of the version even if Syntastic wasn't loaded from the start.

**Comment by lcd047** [comment]
Please try this commit instead: 9ed5763b.

**Comment by Tav0** [comment]
Sure, thank you.

**Pull request closed without merging**
