### PR TITLE
Checker haskell/hlint: supress colors

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by lcd047** [comment]
What problem are you trying to solve?

**Comment by phadej** [comment]
`hlint` might have configuration which forces colored output, even when terminal doesn't support it. This makes `hlint` not emit color codes.

I don't know if it's better to strip ANSI color codes, but I don't know how to do that.

**Comment by lcd047** [comment]
The downside to this change is that option `--color` is supported only since hlint version v1.9.4.  Your patch needs to take that into account.

**Comment by phadej** [comment]
The command line parsing library which `hlint` uses, got support for `--numeric-version` in

```
0.10.8, released 2014-07-21
    Avoid compilation warnings on GHC 7.8
    #9, add --numeric-version flag
```

It's unfortunately not tied to `hlint`'s version.

The `--version` flag outputs something like

```
HLint v2.1.15, (C) Neil Mitchell 2006-2019
```

which I don't know how to parse with `vimscript`

**Comment by lcd047** [comment]
Ok, please try 1089ee52.

**Comment by phadej** [comment]
@lcd047 that works, thanks!

**Pull request closed without merging**
