### PR TITLE
Update compile.py - change default python to python3

### PR DESCRIPTION
**Pull request by mimi1vx**

### CODE REVIEW

**Comment by lcd047** [comment]
Your change has literally no effect.  What problem are you trying to solve?

**Comment by mimi1vx** [comment]
@lcd047 my change has pretty big effect, instead calling python2 to check syntax it uses python3 which has now pretty different syntax + is developed.

Py2 is going to die ...

**Comment by lcd047** [comment]
Your change has no effect on syntastic.  To see that, please open a Python script, set `g:syntastic_debug` to 1, run `:SyntasticCheck python`, run `:mes`, and post the output.

**Comment by mimi1vx** [comment]
oh, you are right ...`makeprg` calls python2 .

```
mtui/commands/downgrade.py" 65L, 1829C
syntastic: 59.392181: g:syntastic_version = '3.9.0-15 (Vim 801, Linux, GUI)'
syntastic: 59.393483: &shell = '/bin/zsh', &shellcmdflag = '-c', &shellpipe = '2>&1| tee', &shellquote = '', &shellredi
r = '>%s 2>&1', &shelltemp = 1, &shellxquote = '', &autochdir = 0, &shellxescape = ''
syntastic: 59.396983: UpdateErrors: python
syntastic: 59.397419: CacheErrors: python
syntastic: 59.398533: g:syntastic_aggregate_errors = 0
syntastic: 59.398888: getcwd() = '/home/mimi/git.suse/mtui'
syntastic: 59.420784: system: command run in 0.007471s
syntastic: 59.421380: CacheErrors: Invoking checker: python/python
syntastic: 59.422514: SyntasticMake: called with options: {'errorformat': '%E%f:%l:%c: %m', 'makeprg': 'python /home/mi
mi/.vim/plugged/syntastic/syntax_checkers/python/compile.py mtui/commands/downgrade.py', 'env': {'TERM': 'dumb'}, 'retu
rns': [0]}
syntastic: 59.453090: system: command run in 0.029985s
syntastic: 59.453733: getLocList: checker python/python returned 0
syntastic: 59.454099: getLocList: checker python/python run in 0.032534s
```

**Comment by mimi1vx** [comment]
so it needs also https://github.com/vim-syntastic/syntastic/blob/master/syntax_checkers/python/python.vim#L52 change this line ?

**Comment by lcd047** [comment]
No.  You need to read the [FAQ][FAQ].  Or, if you insist to fix only 1/10th of the problem, set `g:syntastic_pthon_python_exec` to `python3`.

[FAQ]: https://github.com/vim-syntastic/syntastic#faqpython

**Comment by mimi1vx** [comment]
Thanks,

I'm blind .. FAQ section 4.11

**Pull request closed without merging**
