### PR TITLE
add racket syntax checker by running `raco expand`, which is far safe…

### PR DESCRIPTION
**Pull request by Nymphium**
add racket syntax checker by running `raco expand`, which is far safer than running `racket`

### CODE REVIEW

**Comment by lcd047** [comment]
Please use `git commit --amend` to fix the commit message for the first patch.  Also, please don't mess with the registry.

**Comment by Nymphium** [comment]
I `rebase`d and push with `--force`.

**Comment by lcd047** [comment]
... which deleted the commit message instead of fixing it...

**Comment by lcd047** [comment]
Also, please add a manual entry.

**Comment by Nymphium** [comment]
Uhh, I add `raco` to the registry and fix the commit message, right?

**Comment by lcd047** [comment]
No.  Please leave alone the registry, add an entry to the manual (`doc/syntastic-checkers.txt`), and fix the commit message.

**Comment by lcd047** [comment]
Sadly, undocumented features are too hard to use for everybody except their author.  Fortunately, writing a syntastic checker is little more than finding the right `errorformat`.  Oh well.

**Pull request closed without merging**
