### PR TITLE
check vue files with stylelint

### PR DESCRIPTION
**Pull request by oprudkyi**
add ability to use stylelint to check *.vue files

### CODE REVIEW

**Comment by lcd047** [comment]
This isn't really needed, you can run `stylelint` against any file with `:SyntasticCheck css/stylelint`.  Syntastic currently doesn't have any `vue`-specific checkers, and there's no point pretending `stylelint` can play that role.  Sorry, but no.

On a side note, syntastic is essentially dead.  You might want to take a look at [ALE][ALE] instead.

[ALE]: https://github.com/dense-analysis/ale

**Comment by oprudkyi** [comment]
Hi @lcd047 

vue file is a bundle of html/js/css/scss https://vuejs.org/v2/guide/single-file-components.html and having stylelint as one of checkers is essential for me. but ok, understood. anyway thank you for useful plugin

**Comment by lcd047** [comment]
Please see `:h 'syntastic_filetype_map'`.

**Comment by oprudkyi** [comment]
yes, I have tried it, but without success
- stylelint breaks without
```
    \ 'vue':  '-f json',
``` 
in syntax_checkers/css/stylelint.vim
- I need both checkers, eslint and stylelint to run over vue files, and syntastic_filetype_map didn't work for me correctly (I don't remember exactly, but it seems like it allowed to use single checker only)

**Comment by lcd047** [comment]
I see.  Ok, merged with this patch on top: 83837a6e.

**Pull request merged**
