### PR TITLE
D-Scanner support

### PR DESCRIPTION
**Pull request by ANtlord**
Hello!

This PR adds one more [D](https://dlang.org) checker based on [D-Scanner](https://github.com/Hackerpilot/Dscanner). I developed extension using Python 3 because D-Scanner provides JSON output. Handling JSON data using Python is easy and choose that language. If usage of Python 3 is critically bad for maintaining Syntastic I can develop the extension using VimSript.

### CODE REVIEW

**Comment by lcd047** [comment]
> I developed extension using Python 3 because D-Scanner provides JSON output.

There are many other checkers in syntastic that parse JSON.  Please use them as templates.

On a quick look, there are a number of other problems with this:

* The license.  I'm not qualified to decide whether this is compatible or not to WTFPL used by the rest of syntastic, and I'd rather not take chances.
* You're not supposed to add checkers to the registry.
* You left debugging messages in `IsAvailable()`.
* You're checking for prerequisites in `GetLocList()`.
* You're building the `loclist` manually.  This is strongly discouraged.
* Code formatting doesn't follow the conventions used elsewhere in syntastic.

In the current form of this checker, sorry but no.  Perhaps you should consider making it an [external checker](https://github.com/vim-syntastic/syntastic/wiki/Syntax-Checker-Guide#external).

**Comment by ANtlord** [comment]
Point me exmple handles JSON using vim script, please. Thank you. I will fix code issues

**Comment by lcd047** [comment]
> Point me exmple handles JSON using vim script, please.

Read the [guide](https://github.com/vim-syntastic/syntastic/wiki/Syntax-Checker-Guide), then head to [`autoload/syntastic/preprocess.vim`](https://github.com/vim-syntastic/syntastic/blob/master/autoload/syntastic/preprocess.vim) and look for functions that call `s:_decode_JSON()`.

**Comment by ANtlord** [comment]
I've made changes according your recommendations @lcd047

**Comment by lcd047** [comment]
Thank you.  Merged, with this patch on top: 75180da.

**Comment by ANtlord** [comment]
Thank you!

**Pull request closed without merging**
